{% set name = "mujoco-python-viewer" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mujoco-python-viewer-{{ version }}.tar.gz
  sha256: 0602ffd47e14e84b90196e09f45bc353a6339dee069fdd70ebb0253913eb849d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - mujoco-python >=2.1.5
    - glfw >=2.5.0
    - imageio
    - pyyaml

test:
  imports:
    - mujoco_viewer
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rohanpsingh/mujoco-python-viewer
  summary: Interactive renderer for MuJoCo Python
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - traversaro
